name: 'Assert Branch Naming Convention'
on:  
  create:
  pull_request:

jobs:
  branch-naming-rules:
    runs-on: ubuntu-latest
    steps:
      - uses: deepakputhraya/action-branch-name@master
        with:
          regex: '^[a-z0-9-]+/[a-z0-9-]+$' # Regex the branch should match. This example enforces grouping
          allowed_prefixes: 'features,defects,stories,users,releases' # All branches should start with the given prefix
          ignore: main,develop # Ignore exactly matching branch names from convention
          min_length: 5 # Min length of the branch name
          max_length: 50 # Max length of the branch name
